export const teamArray = [
{name: 'Kansas', seed: 1, correct: 'correct'},
{name: 'Gonzaga', seed: 16, correct: 'correct'},
{name: 'Baylor', seed: 8, correct: 'correct'},
{name: 'Dayton', seed: 9, correct: 'correct'},
{name: 'Duke', seed: 5, correct: 'correct'},
{name: 'SDSU', seed: 12, correct: 'correct'},
{name: 'Mich St.', seed: 4, correct: 'correct'},
{name: 'Ohio St.', seed: 13, correct: 'correct'},
{name: 'Louisville', seed: 6, correct: 'correct'},
{name: 'WVU', seed: 11, correct: 'correct'},
{name: 'Maryland', seed: 3, correct: 'correct'},
{name: 'Creighton', seed: 14, correct: 'correct'},
{name: 'BYU', seed: 7, correct: 'correct'},
{name: 'Houston', seed: 10, correct: 'correct'},
{name: 'Florida St.', seed: 2, correct: 'correct'},
{name: 'Michigan', seed: 15, correct: 'correct'},
{name: 'Oregon', seed: 1, correct: 'correct'},
{name: 'Villanova', seed: 16, correct: 'correct'},
{name: 'Arizona', seed: 8, correct: 'correct'},
{name: 'Seton Hall', seed: 9, correct: 'correct'},
{name: 'Texas Tech', seed: 5, correct: 'correct'},
{name: 'Wisconsin', seed: 12, correct: 'correct'},
{name: 'Iowa', seed: 4, correct: 'correct'},
{name: 'Purdue', seed: 13, correct: 'correct'},
{name: 'Butler', seed: 6, correct: 'correct'},
{name: 'Penn St.', seed: 11, correct: 'correct'},
{name: 'Minnesota', seed: 3, correct: 'correct'},
{name: 'Rutgers', seed: 14, correct: 'correct'},
{name: 'Kentucky', seed: 7, correct: 'correct'},
{name: 'Illinois', seed: 10, correct: 'correct'},
{name: 'Marquette', seed: 2, correct: 'correct'},
{name: 'Florida', seed: 15, correct: 'correct'},
{name: 'Auburn', seed: 1, correct: 'correct'},
{name: 'Indiana', seed: 16, correct: 'correct'},
{name: 'Colorado', seed: 8, correct: 'correct'},
{name: 'Oklahoma', seed: 9, correct: 'correct'},
{name: 'LSU', seed: 5, correct: 'correct'},
{name: 'St. Marys', seed: 12, correct: 'correct'},
{name: 'Wichita St.', seed: 4, correct: 'correct'},
{name: 'Providence', seed: 13, correct: 'correct'},
{name: 'Utah St.', seed: 6, correct: 'correct'},
{name: 'Virginia', seed: 11, correct: 'correct'},
{name: 'Stanford', seed: 3, correct: 'correct'},
{name: 'Cincinnati', seed: 14, correct: 'correct'},
{name: 'Xavier', seed: 7, correct: 'correct'},
{name: 'Richmond', seed: 10, correct: 'correct'},
{name: 'Arkansas', seed: 2, correct: 'correct'},
{name: 'Miss St.', seed: 15, correct: 'correct'},
{name: 'Northern Iowa', seed: 1, correct: 'correct'},
{name: 'N.C. State', seed: 16, correct: 'correct'},
{name: 'Syracuse', seed: 8, correct: 'correct'},
{name: 'UConn', seed: 9, correct: 'correct'},
{name: 'Ok St.', seed: 5, correct: 'correct'},
{name: 'Washington', seed: 12, correct: 'correct'},
{name: 'USC', seed: 4, correct: 'correct'},
{name: 'ETSU', seed: 13, correct: 'correct'},
{name: 'Notre Dame', seed: 6, correct: 'correct'},
{name: 'Yale', seed: 11, correct: 'correct'},
{name: 'Memphis', seed: 3, correct: 'correct'},
{name: 'Alabama', seed: 14, correct: 'correct'},
{name: 'Texas', seed: 7, correct: 'correct'},
{name: 'Saint Louis', seed: 10, correct: 'correct'},
{name: 'Arizona St.', seed: 2, correct: 'correct'},
{name: 'Georgia Tech', seed: 15, correct: 'correct'},
];

export const results = [
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
  {name: '', seed: ''},
]
